"""
Job Assignment — Daily cluster assignment job.

Reads embeddings that were already generated by job_embedding, assigns them to
pre-trained clusters via the KMeans N1 model + cluster mapping, enriches with
cluster names, and writes the final output to the clusters_output Iceberg table.

Pre-requisites (must run BEFORE this job):
    - job_embedding  → embeddings table must be populated for today's phrases
    - job_training   → models must exist in S3, cluster_mapping in Iceberg

Idempotent: the output is overwritten per run (or appended depending on config).
Does NOT generate embeddings — that is exclusively job_embedding's responsibility.
"""

from datetime import datetime, timezone

from pyspark.ml.clustering import KMeansModel
from pyspark.ml.feature import NormalizerModel, PCAModel
from pyspark.sql import functions as F

from clustering_pipeline.config.settings import PipelineSettings
from clustering_pipeline.core.base_job import BaseJob
from clustering_pipeline.services.clustering_service import ClusteringService, SparkKMeansStrategy
from clustering_pipeline.services.storage_service import IcebergStorageService
from clustering_pipeline.utils.logger import PipelineLogger
from clustering_pipeline.utils.validators import InputValidator


class JobAssignment(BaseJob):
    """
    Daily cluster assignment job.

    Assumes embeddings for today's phrases are already present in the
    embeddings table (produced by job_embedding).

    Phases:
        1. Load today's embeddings + cluster_mapping + cluster_names + S3 models
        2. Assign cluster_n1 via pre-trained KMeans model
        3. Join cluster_mapping → cluster_n2, cluster_n3
        4. Join cluster_names → nome_n1/dor_n1, nome_n2/dor_n2, nome_n3/dor_n3
        5. Write enriched output to clusters_output
    """

    def __init__(self, settings: PipelineSettings):
        super().__init__(settings)
        self.logger = PipelineLogger(job_name=self.job_name, service_name="JobAssignment")

    @property
    def job_name(self) -> str:
        return "job_assignment"

    # ------------------------------------------------------------------
    # Validate
    # ------------------------------------------------------------------

    def validate_inputs(self) -> bool:
        """
        Validate pre-conditions:
        - S3 model paths are accessible (normalizer, pca, kmeans_n1).
        - cluster_mapping and frases_raw tables exist.
        - Embeddings table exists and is non-empty.
        """
        validator = InputValidator(
            PipelineLogger(self.job_name, "InputValidator")
        )
        cfg = self.settings.storage

        # S3 models
        for path in [
            cfg.model_normalizer_path,
            cfg.model_pca_path,
            cfg.model_kmeans_n1_path,
        ]:
            validator.assert_s3_path_accessible(self.spark, path)

        # Required Iceberg tables
        for table in [cfg.table_cluster_mapping, cfg.table_embeddings]:
            validator.assert_table_exists(self.spark, table)

        df_emb = self.spark.table(cfg.table_embeddings)
        validator.assert_not_empty(df_emb, "embeddings")

        return True

    # ------------------------------------------------------------------
    # Run
    # ------------------------------------------------------------------

    def run(self) -> None:
        """Execute all assignment phases."""
        cfg = self.settings
        processed_at = datetime.now(tz=timezone.utc)
        today = str(processed_at.date())

        storage_svc = IcebergStorageService(
            spark=self.spark,
            config=cfg.storage,
            logger=PipelineLogger(self.job_name, "IcebergStorageService"),
        )
        clustering_svc = ClusteringService(
            spark=self.spark,
            strategy=SparkKMeansStrategy(cfg.clustering),
            config=cfg.clustering,
            logger=PipelineLogger(self.job_name, "ClusteringService"),
        )

        # ── PHASE 1: Load data + models ────────────────────────────────
        self.logger.info("FASE 1 — Carregando embeddings do dia e modelos")

        df_embeddings = storage_svc.read_table_with_filter(
            cfg.storage.table_embeddings,
            f"date(created_at) = date('{today}')",
        )
        total_embeddings = df_embeddings.count()

        df_cluster_mapping = storage_svc.read_table(cfg.storage.table_cluster_mapping)

        cluster_names_exists = storage_svc.table_exists(cfg.storage.table_cluster_names)
        df_cluster_names = (
            storage_svc.read_table(cfg.storage.table_cluster_names)
            if cluster_names_exists
            else None
        )

        self.logger.info(
            "Carregando modelos do S3",
            normalizer=cfg.storage.model_normalizer_path,
            pca=cfg.storage.model_pca_path,
            kmeans_n1=cfg.storage.model_kmeans_n1_path,
        )
        normalizer_model = NormalizerModel.load(cfg.storage.model_normalizer_path)
        pca_model = PCAModel.load(cfg.storage.model_pca_path)
        kmeans_n1_model = KMeansModel.load(cfg.storage.model_kmeans_n1_path)

        self.logger.info(
            "Fase 1 concluída",
            embeddings_do_dia=total_embeddings,
            data=today,
        )

        # ── PHASE 2–3: Assign clusters ─────────────────────────────────
        self.logger.info("FASE 2 — Atribuindo clusters (N1 + mapeamento N2/N3)")
        df_clustered = clustering_svc.transform_new_embeddings(
            df=df_embeddings,
            normalizer_model=normalizer_model,
            pca_model=pca_model,
            kmeans_n1_model=kmeans_n1_model,
            cluster_mapping=df_cluster_mapping,
            features_col="embedding",
        )
        self.logger.info("Clusters atribuídos")

        # ── PHASE 4: Enrich with cluster names ─────────────────────────
        if df_cluster_names is not None:
            self.logger.info("FASE 3 — Enriquecendo com nomes de clusters")
            n1_names = df_cluster_names.filter(F.col("nivel") == 1).select(
                F.col("cluster_id").alias("cluster_n1"),
                F.col("nome").alias("nome_n1"),
                F.col("dor").alias("dor_n1"),
            )
            n2_names = df_cluster_names.filter(F.col("nivel") == 2).select(
                F.col("cluster_id").alias("cluster_n2"),
                F.col("nome").alias("nome_n2"),
                F.col("dor").alias("dor_n2"),
            )
            n3_names = df_cluster_names.filter(F.col("nivel") == 3).select(
                F.col("cluster_id").alias("cluster_n3"),
                F.col("nome").alias("nome_n3"),
                F.col("dor").alias("dor_n3"),
            )
            df_clustered = (
                df_clustered
                .join(n1_names, on="cluster_n1", how="left")
                .join(n2_names, on="cluster_n2", how="left")
                .join(n3_names, on="cluster_n3", how="left")
            )
            self.logger.info("Nomes de clusters adicionados")
        else:
            self.logger.warning(
                "Tabela cluster_names não encontrada — output sem nomes de clusters"
            )

        # ── PHASE 5: Write output ──────────────────────────────────────
        self.logger.info("FASE 4 — Salvando output final em clusters_output")
        df_output = df_clustered.withColumn(
            "processed_at", F.lit(processed_at).cast("timestamp")
        )

        storage_svc.write_table(
            df=df_output,
            table_name=cfg.storage.table_clusters_output,
            mode="append",
        )

        self.logger.info(
            "RESUMO — JobAssignment concluído",
            registros_salvos=total_embeddings,
            data=today,
            colunas=df_output.columns,
        )


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    settings = PipelineSettings.from_env()
    job = JobAssignment(settings)
    job.execute()
